### ISSUE TITLE
precompile not applying app/overrides/* when running precompile with RAILS_ENV=production

### ISSUE THREAD

**Issue by sybind** [spree/deface#151]
The overrides I created in app/overrides/ are not applied to the compiled_views if I specify the production environment in RAILS_ENV when running rake task for precompile, such as:

```
RAILS_ENV=production bundle exec rake deface:precompile
```

**Comment by johnwook** [comment]
I think your `production.rb` file might include this.

```
config.deface.enabled = false
```

In that case, deface will not work. You have to precompile deface resources in other environments(i.e. development, **not** production) then commit(and/or push) your precompiled assets.
