### ISSUE TITLE
NoMethodError: undefined method `=~' for #<Pathname>

### ISSUE THREAD

**Issue by ondra-m** [spree/deface#156]
Some rails engines are using Pathname instead of String on `config.eager_load_paths`

Result is

```
NoMethodError: undefined method `=~' for #<Pathname>
deface-1.0.2/lib/deface/railtie.rb:50:in `block (3 levels) in <class:Railtie>'
deface-1.0.2/lib/deface/railtie.rb:50:in `reject!'
deface-1.0.2/lib/deface/railtie.rb:50:in `block (2 levels) in <class:Railtie>'
deface-1.0.2/lib/deface/railtie.rb:48:in `each'
deface-1.0.2/lib/deface/railtie.rb:48:in `block in <class:Railtie>'
```

**Comment by rhulka** [comment]
maybe this can be useful to someone, I have made following workaround to avoid this issue https://github.com/rhulka/deface/commit/f517f34444d11d20fd0adc208fab5e36bc9eca16 (just converting object to string)

I use this gem as dependency in redmine plugin 
  Redmine version                3.2.0.stable
  Ruby version                   2.0.0-p643 (2015-02-25) [x86_64-linux]
  Rails version                  4.2.5.1

**Comment by damianlegawiec** [comment]
Hi @rhulka can you do a PR with this change? Thanks!
