### ISSUE TITLE
Error on nokogiri dependences

### ISSUE THREAD

**Issue by marcellovetro** [spree/deface#167]
It's using an older version of nokogiri (now 1.7), please update dependences in 

from nokogiri (~> 1.6.0) to nokogiri (>= 1.6.0)
 
![image](https://cloud.githubusercontent.com/assets/4971888/23330447/2956e8e2-fb4e-11e6-9b1c-eda84fa52a1e.png)

**Comment by domcleal** [comment]
https://github.com/spree/deface/commit/8451d46680f6e9484d18ca6fe31bd024bd60874a does this, but it's pending release of a new gem.

**Comment by damianlegawiec** [comment]
@marcellovetro  @domcleal deface 1.2.0 was released to RubyGems on March 20
