### ISSUE TITLE
Deface requires vulnerable version of nokogiri

### ISSUE THREAD

**Issue by hxegon** [spree/deface#170]
I found this with bundle audit using 1.0.2, but the new versions also require nokogiri ~> 1.6.x, which is vulnerable.

More info here: https://github.com/sparklemotion/nokogiri/issues/1582

**Comment by domcleal** [comment]
Newer versions (i.e. deface 1.2.0) require `~> 1.6`, which permits the very latest version of nokogiri, 1.7.1.
