### ISSUE TITLE
deprecation: refresh is deprecated and will be removed from Rails 6.1

### ISSUE THREAD

**Issue by elia** [spree/deface#204]
Rails 6 is reporting this deprecation:

```
DEPRECATION WARNING: refresh is deprecated and will be removed from Rails 6.1 (called from render at /Users/elia/.rvm/rubies/ruby-2.7.0/lib/ruby/gems/2.7.0/gems/deface-1.5.3/lib/deface/action_view_extensions.rb:41)
```

The PR introducing the deprecation is https://github.com/rails/rails/pull/35865

**Comment by elia** [comment]
**Update:** the effect of that rails PR is that refreshing deface overrides no longer works in development with Rails 6, we verified that on multiple apps/extensions.

I'm digging into the deface and actionview code to see if there's a way out of this with the new AV File API, I'll report back once I find something or I have a working PR 🔍

**Comment by hoshinotsuyoshi** [comment]
I ran into this problem in Rails 6.1.

As this issue title mentions, this method `ActionView::Template#refresh` was removed, so it causes error.

----

### error in Rails 6.1 (development mode)

<img width="1010" alt="42" src="https://user-images.githubusercontent.com/1394049/107100187-fa416d00-6856-11eb-964b-2db841fff192.png">

```
undefined method `refresh' for #<ActionView::Template:0x00007f5a475b3a30>
```


```
deface (1.6.1) lib/deface/action_view_extensions.rb:44:in `render'
actionview (6.1.1) lib/action_view/renderer/partial_renderer.rb:285:in `block in render_partial_template'
activesupport (6.1.1) lib/active_support/notifications.rb:203:in `block in instrument'
....
```
