### ISSUE TITLE
Issue with slim templates in 1.7.0

### ISSUE THREAD

**Issue by storm2513** [spree/deface#217]
After updating from 1.6.2 to 1.7.0 rails started rendering slim templates as plain files (as it is, without conversion to html)

**Comment by zernie** [comment]
Same here

**Comment by retsef** [comment]
I have got the same issue, but with haml templates. For now i rolled back to 1.6.x

**Comment by elia** [comment]
Can you please try with revision `85ddb7ac1f3946c6e596c770256ef6bbb70e0060` and see if the problem is already present there?

```rb
gem "deface", git: "https://github.com/spree/deface.git", ref: "85ddb7ac1f3946c6e596c770256ef6bbb70e0060"
```

**Comment by hoshinotsuyoshi** [comment]
> https://github.com/spree/deface/issues/217#issuecomment-784996323

👋  I've got the same issue too.  **haml**.

Environment:
ruby 3.0.0
rails 6.1.3
haml-rails 2.0.1
haml 5.2.1



> Can you please try with revision `85ddb7ac1f3946c6e596c770256ef6bbb70e0060` and see if the problem is already present there?
> 
> ```ruby
> gem "deface", git: "https://github.com/spree/deface.git", ref: "85ddb7ac1f3946c6e596c770256ef6bbb70e0060"
> ```

I tried that revision. 
My spree app seems to be working :)

**Comment by elia** [comment]
I just opened https://github.com/spree/deface/pull/218 which should fix the issue, can any of you confirm it's working and report the version of Rails you tried it on?

**Comment by elia** [comment]
I just released v1.8.0, can you confirm it fixes the issue?

**Comment by zernie** [comment]
@elia nope. still happens sometimes

**Comment by elia** [comment]
@zernie is it sometimes or all the time with some templates/overrides?

I'm looking for anything that can help reproducing the issue.

**Comment by zernie** [comment]
@elia practically all the time. I'm using it in a solidus project

**Comment by elia** [comment]
Thanks, I'll look into it tomorrow (I hope).

**Comment by elia** [comment]
@zernie I'm unable to reproduce the issue, can you please try and see if you can reproduce it on the deface sandbox app? Maybe it's a specific version combination or something on those lines.

To run the sandbox app:

- checkout the deface repo
- run `bin/setup` to install dependencies
- run `bin/rails s` (this will build and start the server for the sandbox app)

An alternative would be to push a demo app that shows the problem.

If you find a way to reproduce the problem or push an app please open a separate issue with specific instructions, mentioning me (@elia) and this issue (#217).
